import type { PropsWithChildren } from "react";
import { Providers } from "@ui/components";
import { Flex } from "@chakra-ui/react";
import classNames from "classnames";
import { plusJakartaSans, roboto } from "@ui/theme/fonts";

export const metadata = {
  title: "Welcome to UI",
  description: "Generated by create-nx-workspace",
};

export default async function RootLayout({ children }: PropsWithChildren) {
  return (
    <html
      lang="en"
      className={classNames(roboto.className, plusJakartaSans.className)}
      data-theme="dark"
      style={{ colorScheme: "dark" }}
    >
      <body className="chakra-ui-dark">
        <Providers>
          <Flex h="100svh" flexDir="column" bgColor="bg.body">
            {children}
          </Flex>
        </Providers>
      </body>
    </html>
  );
}
