import type { PropsWithChildren } from "react";
import { Navbar, Paper, Providers } from "@ui/components";
import { Inter, Roboto } from "next/font/google";
import { Box, Flex, Heading } from "@chakra-ui/react";
import classNames from "classnames";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Welcome to UI",
  description: "Generated by create-nx-workspace",
};

export default async function RootLayout({ children }: PropsWithChildren) {
  return (
    <html
      lang="en"
      className={classNames(inter.className, roboto.className)}
      data-theme="dark"
      style={{ colorScheme: "dark" }}
    >
      <body className="chakra-ui-dark">
        <Providers>
          <Flex h="100svh" flexDir="column" bgColor="bg.body">
            <Box w="full" h="full" overflow="auto">
              {children}
            </Box>
            <Navbar />
          </Flex>
        </Providers>
      </body>
    </html>
  );
}
