services:
  db:
    image: postgres:latest
    container_name: dyf_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
  api:
    container_name: dyf_api
    image: zeilar/did-you-forget_api:latest
    depends_on:
      - db
    expose:
      - 4020:4020
  ui:
    container_name: dyf_ui
    image: zeilar/did-you-forget_ui:latest
    expose:
      - 4025:4025

volumes:
  postgres_data:
