services:
  db:
    image: postgres:latest
    container_name: dyf_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer:latest
    container_name: dyf_adminer
    ports:
      - 8080:8080

volumes:
  postgres_data:
